### PR TITLE
Setting attr_readonly to belongs_to filed must be OK

### PR DESCRIPTION
**Pull request by hiroshi**
Just add a failed example.
<a href="https://gyazo.com/4d561a5d287293a1e29ed83ec9a1a0ab">https://gyazo.com/4d561a5d287293a1e29ed83ec9a1a0ab</a>

### CODE REVIEW

**Comment by hiroshi** [comment]
I think it is better to write a failed example and let a CI explains behave of me.
I'll create a jira ticket if you please.

If you are kind enough, please give me insight about where to be fixed or just push a commit.

**Comment by estolfo** [comment]
Hi @hiroshi 
Thank you for reporting this. I think the expected behavior is that foreign key fields cannot be attr_readonly. ActiveRecord ignores it:

```ruby
class Child < ApplicationRecord
  attr_readonly :mother_id
  belongs_to :mother
end

class Mother < ApplicationRecord
  has_many :children
end

2.4.1 :001 > c = Child.new
 => #<Child id: nil, mother_id: nil, created_at: nil, updated_at: nil, name: nil> 
2.4.1 :002 > m = Mother.new
 => #<Mother id: nil, created_at: nil, updated_at: nil> 
2.4.1 :003 > c.mother = m
 => #<Mother id: nil, created_at: nil, updated_at: nil> 
2.4.1 :004 > c.save
   (0.1ms)  begin transaction
  SQL (0.4ms)  INSERT INTO "mothers" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2017-06-30 05:47:37.580014"], ["updated_at", "2017-06-30 05:47:37.580014"]]
  SQL (0.2ms)  INSERT INTO "children" ("mother_id", "created_at", "updated_at") VALUES (?, ?, ?)  [["mother_id", 9], ["created_at", "2017-06-30 05:47:37.589372"], ["updated_at", "2017-06-30 05:47:37.589372"]]
   (1.4ms)  commit transaction
 => true 
2.4.1 :005 > c.id
 => 6 
2.4.1 :006 > m.id
 => 9 
2.4.1 :007 > m2 = Mother.new
 => #<Mother id: nil, created_at: nil, updated_at: nil> 
2.4.1 :008 > m2.save
   (0.1ms)  begin transaction
  SQL (2.4ms)  INSERT INTO "mothers" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2017-06-30 05:47:46.046904"], ["updated_at", "2017-06-30 05:47:46.046904"]]
   (1.4ms)  commit transaction
 => true 
2.4.1 :009 > m2.id
 => 10 
2.4.1 :010 > c.mother = m2
 => #<Mother id: 10, created_at: "2017-06-30 05:47:46", updated_at: "2017-06-30 05:47:46"> 
2.4.1 :012 > c.save
   (0.1ms)  begin transaction
  SQL (0.5ms)  UPDATE "children" SET "mother_id" = ?, "updated_at" = ? WHERE "children"."id" = ?  [["mother_id", 10], ["updated_at", "2017-06-30 05:47:54.513353"], ["id", 6]]
   (1.5ms)  commit transaction
 => true 
2.4.1 :013 > c.reload
  Child Load (0.3ms)  SELECT  "children".* FROM "children" WHERE "children"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
 => #<Child id: 6, mother_id: 10, created_at: "2017-06-30 05:47:37", updated_at: "2017-06-30 05:47:54", name: nil> 
2.4.1 :014 > c.mother.id
  Mother Load (0.3ms)  SELECT  "mothers".* FROM "mothers" WHERE "mothers"."id" = ? LIMIT ?  [["id", 10], ["LIMIT", 1]]
 => 10
```

Mongoid should do the same so I've opened [this pull request](https://github.com/mongodb/mongoid/pull/4438) against the 6.2.0-stable branch. Do you agree that this is the expected behavior?

Thanks
Emily

**Comment by hiroshi** [comment]
Hi @estolfo 

Thanks for your explanation.

I hadn't been aware that ActiveRecored has same `attr_readonly`.
http://api.rubyonrails.org/classes/ActiveRecord/ReadonlyAttributes/ClassMethods.html
> Attributes listed as readonly will be used to create a new record but update operations will ignore these fields.

From this description, I think ActiveRecord should `ignore` a new value of a `attr_readonly` field to be saved. So, exact same rule should be used for belongs_to keys as we expected.
I think you found a bug of ActiveRecord.


My case is not that belongs_to fields about to be saved, but just referencing a belongs_to `document`.
With mongoid 5.2 the example in this PR should pass, but with 6.2 it doesn't. This is a regression I think.

See https://github.com/mongodb/mongoid/pull/4435/files#diff-6398be3f30b0559e05213d9b521dc8cfR319
It just references belongs_to document.

**Comment by estolfo** [comment]
Hi @hiroshi 
Thank you for pointing out that the behavior changed between 5.x and 6.x. I've found that it changed as a result of [this ticket](https://jira.mongodb.org/browse/MONGOID-3535), i.e. [this commit](https://github.com/mongodb/mongoid/commit/86adca360dc5ae28aee289c6761b60dbc6f20d00).

I will look into a solution and have an update soon.
Thanks!
Emily

**Comment by estolfo** [comment]
Hi @hiroshi 

I've opened a pull request correcting Mongoid's behavior to match that of ActiveRecord. You can see the gist [here](https://gist.github.com/estolfo/01933abfff69bfb54c3336281b611780) documenting AR's behavior.

The pull request is [here](https://github.com/mongodb/mongoid/pull/4439). Your test passes with it.

The change will go into Mongoid 7.0, as it's a behavior change.

Let me know if you have any more questions. Thanks!

Emily

**Comment by hiroshi** [comment]
Thanks for your work.
It will be great to make mongoid behaves like ActiveRecord as possible.

However, it seems that https://github.com/mongodb/mongoid/pull/4439 is about persistence behaviors, but my claim is that "just referencing a belongs_to relation, raise an error if the key of belongs_to is attr_readeonly". I don't trying to SAVE a document.

```ruby
mother = Person.create
Person.create(mother: mother)
child = Person.find_by(mother: mother)
expect {
  child.mother
}.not_to raise_error
```

You said that this test will pass with https://github.com/mongodb/mongoid/pull/4439, it will be OK if so, but why don't you add the exact test of my problem?

Anyway, I thank you for taking time to listen a user's opinion :-)

**Comment by estolfo** [comment]
Hi @hiroshi 

I've added a test for your exact scenario [in this commit.](https://github.com/mongodb/mongoid/pull/4439/commits/9e3f55be005273f9c7aad61f762439b00ab52eca)

Let me know if everything looks ok now and if this can be merged. Thank you for your help and patience!
Emily

**Comment by hiroshi** [comment]
https://github.com/mongodb/mongoid/pull/4439/commits/9e3f55be005273f9c7aad61f762439b00ab52eca
Those examples looks great for me.
I appreciate your work.

Thanks 😄

**Comment by estolfo** [comment]
great, thanks @hiroshi !

**Comment by estolfo** [comment]
replaced by https://github.com/mongodb/mongoid/pull/4439

**Pull request closed without merging**
