### PR TITLE
MONGOID-5266 Deprecate JRuby support


### PR DESCRIPTION
**Pull request by p-mongo**

### CODE REVIEW

**Comment by johnnyshields** [comment]
Why?

**Comment by p-mongo** [comment]
https://jira.mongodb.org/browse/MONGOID-5266

**Comment by p-mongo** [comment]
@johnnyshields The reasoning is given in https://jira.mongodb.org/browse/RUBY-2781.

**Review by Neilshweky — APPROVED** [review]

**Comment by johnnyshields** [comment]
@p-mongo please hold off on merging this until there is more community engagement about JRuby. There have already been JRuby users commenting in the thread.

**Comment by p-mongo** [comment]
@johnnyshields There should be a response appearing soon in https://jira.mongodb.org/browse/RUBY-2781, please continue the discussion there so that it is in one place.

The plan right now is to deprecate JRuby support in Mongoid 7 and to remove it in Mongoid 8. This PR (the deprecation) is easy to revert if needed. With that said, https://jira.mongodb.org/browse/RUBY-2781 outlines reasons why the tearm is removing JRuby support.

**Pull request merged**
