### PR TITLE
Add support for .inc to contextual

### PR DESCRIPTION
**Pull request by johnnyshields**
Allows inc to be used with embedded docs.

### CODE REVIEW

**Comment by simi** [comment]
Looks ok, anyway is it possible to include spec? I can help with that if needed.

**Comment by johnnyshields** [comment]
@simi please help

**Comment by estolfo** [comment]
yes, a spec would be great, thanks.

**Comment by estolfo** [comment]
I've added a spec in this commit: https://github.com/mongodb/mongoid/commit/20f8bcf4789665c9ba9124e0f00174b7193fcd05

**Pull request merged**
