### PR TITLE
Allow cache timestamp format to be changed like in ActiveRecord.

### PR DESCRIPTION
**Pull request by DouweM**
See https://github.com/rails/rails/blob/master/activerecord/lib/active_record/integration.rb#L14

### CODE REVIEW

**Comment by estolfo** [comment]
Hey @DouweM 
Is there any chance you can rebase against master so we can merge this?
Thanks!

**Comment by DouweM** [comment]
@estolfo GitHub shows "This branch has no conflicts with the base branch", it should already be mergeable.

**Comment by estolfo** [comment]
yes, but if you rebase we can see the tests run on travis.

**Comment by estolfo** [comment]
cherry-picked to master https://github.com/mongodb/mongoid/commit/f69c9a3ea50f0d59c54d38a05c8e56132c277242

**Pull request closed without merging**
