### PR TITLE
🚀 MONGOID-5579: Mongoid 9.0: Require minimum DB version 4.2+

### PR DESCRIPTION
**Pull request by johnnyshields**
Mongoid 9.0 should drop support for MongoDB 4.0 and prior, which are already past EOL. Users should **not** use these server versions, but if they insist on remaining on EOL, they can stay on Mongoid 8.x which will continue to get critical support for some time.

This PR does all the following:
- Remove `Criteria#geo_near` and `GeoNear` etc. classes. These no longer work on MongoDB 4.2+
- Remove `Criteria#max_scan`. This no longer works on MongoDB 4.2+
- Remove the `:background_indexing` global option and `:background` index specification arg. These no longer work on MongoDB 4.2+
- Make documentation section "Embedded Matching vs Server Behavior" more terse in light of the changes.
- Mark server versions 3.6 and 4.0 as deprecated as of Mongoid 8.1 (will be backported)
- Update list of supported `auth_mechs` values (out-of-sync with driver, does not reflect latest server support)
- Remove server runs of 3.6 and 4.0 from Evergreen and Github CI
- Remove various references to server versions 4.0 and prior in docs and test definitions.

### CODE REVIEW

**Comment by johnnyshields** [comment]
Merged to [Ultra](https://github.com/tablecheck/mongoid-ultra)

**Comment by johnnyshields** [comment]
This can be rebased after https://github.com/mongodb/mongoid/pull/5762 is merged.

**Comment by alexbevi** [comment]
Since 9.0 has already been released we can close this out.

**Comment by johnnyshields** [comment]
@alexbevi please re-open. Support for MongoDB 4.0 has not yet been dropped; this should be done in MongoDB 10.0

**Pull request closed without merging**
