### PR TITLE
MONGOID-5268 Remove JRuby support


### PR DESCRIPTION
**Pull request by p-mongo**

### CODE REVIEW

**Comment by p-mongo** [comment]
https://jira.mongodb.org/browse/MONGOID-5268

**Comment by johnnyshields** [comment]
Why is this being pushed through without community consultation?

**Review by Neilshweky — COMMENTED** [review]
I found some references to JRuby that you haven't removed... `app_spec.rb:29` talks about seeing a longer timeout for jruby, `lite_spec_helper.rb:11` mentions jruby also. 

It looks like we did something in `options_spec:12` as well to conform with jruby. 

Are these intended to be left in?

**Review by Neilshweky — APPROVED** [review]

**Comment by headius** [comment]
Is there some reason JRuby support is being dropped?

The changes here all seem very minimal and mostly you are just removing it from the test matrix. I saw comments about long test run times, with which we would be happy to help.

Is there something else driving this?

**Comment by johnnyshields** [comment]
@headius -- you may also wish to comment on this epic: https://jira.mongodb.org/browse/RUBY-2781

**Comment by headius** [comment]
@johnnyshields Thank you for that link! I understand some of the justification for dropping JRuby support, but it is shocking to me that this is being done without ever reaching out to the JRuby team, the JRuby account on twitter, or our chat room and mailing list. We are willing to help maintain libraries, either by pulling in community resources or by contributing directly, and we very much do not want to see this removal go forward.

**Pull request closed without merging**
