### PR TITLE
MONGOID-5596 - Mongoid 8.1: Deprecate Mongoid::QueryCache in favor of Mongo::QueryCache

### PR DESCRIPTION
**Pull request by johnnyshields**

### CODE REVIEW

**Comment by johnnyshields** [comment]
@comandeo did another PR for this so closing.

**Comment by comandeo** [comment]
For some reason there was no link to your PR in the ticket, so I missed it. Actually, your implementation looks more thorough! Let's work on this PR instead of the tone I opened.

**Comment by johnnyshields** [comment]
Sure, it's all yours!

**Comment by comandeo** [comment]
@johnnyshields I would like to merge the latest 8.1-stable into your branch. It does not let me do non-fast-forward push, and I am hesitant to do a force push to your branch. Could you please either merge 8.1-stable from the upstream, or give me a green light to do force push? Thank you!

**Comment by comandeo** [comment]
Closing in favor of https://github.com/mongodb/mongoid/pull/5654, which is an exact copy of this one, but with the actual `8.1-stable` merged.

**Pull request closed without merging**
