### PR TITLE
MONGOID-5579 Mongoid 8.1: Ruby, JRuby, Rails and MongoDB Server version support adjustments

### PR DESCRIPTION
**Pull request by johnnyshields**
This PR adds the following to Mongoid 8.1:
- Add support for Ruby 3.2 and JRuby 9.4, include notice in release notes and CI tests for Ruby 3.2 and JRuby 9.4 (Evergreen and Github).
   - No `/lib/` code changes are required for these to work (PR #5470 affecting only specs is backported here.)
   - I've been running Ruby 3.2 on Mongoid 7.5 in production for several months.
- Add additional coverage of MongoDB server 6.0 to CI which is missing in some places.
- Deprecation notice of MongoDB Server 3.6 and 4.0, Ruby 2.6, JRuby 9.3, Rails 5.2.
- Deprecation of GeoNear class, index :background option, and Criteria#max_scan methods, all of which don't work on MongoDB Server 4.2+
- Update to compatibility table in documentation.
- Includes PR https://github.com/mongodb/mongoid/pull/5572 fix for deprecation logic in order to get specs to pass.

Refer to https://github.com/mongodb/mongoid/pull/5567 for the removal of some of these deprecations in Mongoid 9.0

Notice that JRuby 9.4 is added and JRuby 9.3 is deprecated. I think it is reasonable for Mongoid 9 to support only JRuby 9.4 given the extra burden JRuby places on MongoDB drivers team.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@jamis this PR would be good to merge next, assuming the team agrees with the version changes here.

**Comment by riseshia** [comment]
ping, any progress on this?

**Comment by johnnyshields** [comment]
TODO: This needs to be restacked as 8.2, since 8.1 was released without it.

**Comment by johnnyshields** [comment]
Closing as this is stale

**Pull request closed without merging**
