### PR TITLE
MONGOID-4218 Support Rails 5

### PR DESCRIPTION
**Pull request by estolfo**

### CODE REVIEW

**Comment by AntiFish03** [comment]
@estolfo, I am trying to use your branch to play with rails-5.0.0.beta1.1 in api_only with mongoid.  I keep getting:

```
Mongoid::Errors::NoClientConfig: 
message:
  No configuration could be found for a client named 'default'.
summary:
  When attempting to create the new client, Mongoid could not find a client configuration for the name: 'default'. This is necessary in order to know the host, port, and options needed to connect.
resolution:
  Double check your mongoid.yml to make sure under the clients key that a configuration exists for 'default'. If you have set the configuration programatically, ensure that 'default' exists in the configuration hash.
```

Yes, config/mongoid.yml does exist and contains the defaults.
Ruby version: ruby-2.3.0
Mongo version: 3.2.1

**Comment by durran** [comment]
@AntiFish03 What's the full stack trace? Is the exception occuring here?: https://github.com/mongodb/mongoid/blob/master/lib/mongoid/railtie.rb#L61

**Comment by AntiFish03** [comment]
@durran, Well I am a little embarrassed... it was my fault. I forgot to restart the server apparently after I added the mongoid.yml.

**Comment by simi** [comment]
Will be both ActiveModel 4.x and ActiveModel 5.x supported in Mongoid 5? I can prepare PR to test against both on CI.

**Comment by durran** [comment]
@simi Only ActiveModel 5.

**Comment by bmalets** [comment]
:+1:

**Pull request merged**
