### PR TITLE
MONGOID-4181 adding spec to prove this is no longer an issue

### PR DESCRIPTION
**Pull request by DiannaHohensee**

### CODE REVIEW

**Comment by estolfo** [comment]
hey @DiannaHohensee can you rebase against master so the tests can run on travis ?

**Comment by jsperezg** [comment]
This still happens when the belongs_to has a touch: true

**Comment by estolfo** [comment]
Hi @jsperezg 

Can you please share what version of Mongoid you are using? I'm not seeing that it's an issue with the latest 6.2.0.

If it's indeed still an issue, can you please reopen the [mongoid ticket](https://jira.mongodb.org/browse/MONGOID-4181) and put steps to reproduce along with the version you are using?

Thanks!

Emily

**Comment by jsperezg** [comment]
Hi, 

You can safely ignore it. I've been experiencing lots of weird issues like 'after_update' triggered after document creation, and regressions like this but my conclusion is that it's a side effect from this gem:

https://github.com/mrrooijen/mongoid-paperclip

**Pull request merged**
