### PR TITLE
MONGOID-2882 Set base object on documents being iterated from criteria and from Association Enumerable

### PR DESCRIPTION
**Pull request by estolfo**

### CODE REVIEW

**Comment by jarthod** [comment]
Can't try this on updown.io yet as it depends on Rails 5 ☹
Hopefully soon ^^

**Comment by estolfo** [comment]
ah, sorry about that @jarthod = (

**Comment by jarthod** [comment]
I plan on upgrading to Rails 5 soon now that dependencies starts to be compatible, so hopefully I'll be able to test this soon ;)

**Comment by estolfo** [comment]
ok, looking forward to your feedback

**Comment by johnnyshields** [comment]
@estolfo what's the status of this?

**Comment by estolfo** [comment]
Closing in favor of https://github.com/mongodb/mongoid/pull/4475

**Pull request closed without merging**
