### PR TITLE
6.0.0: Use Refinements instead of Extensions in Global Namespace

### PR DESCRIPTION
**Pull request by durran**

### CODE REVIEW

**Comment by simi** [comment]
You'll need to update JRuby to 9000 on CI to test refinements there.

**Comment by johnnyshields** [comment]
Please consider merging https://github.com/mongodb/mongoid/pull/4164 first as it's likely to conflict with this.

**Comment by durran** [comment]
@johnnyshields Ah thanks for reminding me of that. Will do.

**Comment by estolfo** [comment]
We're not going to use Refinements in Mongoid, they're not fully supported by RRuby.

**Pull request closed without merging**
