### PR TITLE
[wip] Add newline to inspectable method

### PR DESCRIPTION
**Pull request by u16suzu**
Mongoid prints data in one line in rails console like following. But I find it a little difficult to read.

```rb
[5] pry(main)> User.first
=> #<User _id: 64002124c849723d04d26d64, created_at: 2023-03-02 04:08:04.369 UTC, updated_at: 2023-03-07 07:05:15.893 UTC, n(name): "test_user", e(email): "test_user@example.com">
```

This PR adds a line break for each field like `ActiveRecord` to make the data easier to read.
Also, this PR move `created_at` and `updated_at` fields to the end like AR.
As a result, it will be displayed as follows.

```rb
[9] pry(main)> User.first
=>
#<User
 _id: 64002124c849723d04d26d64,
 n(name): "test001",
 e(email): "test@st.inc">
 created_at: 2023-03-02 04:08:04.369 UTC,
 updated_at: 2023-03-07 07:05:15.893 UTC>
```

### CODE REVIEW

**Comment by u16suzu** [comment]
hum should I create a evergreen account and make issue ticket on evergreen?

**Comment by alexbevi** [comment]
> hum should I create a evergreen account and make issue ticket on evergreen?

Hi @u16suzu. No need for this at the moment, however if you'd like to open a ticket for the [MONGOID project](https://jira.mongodb.org/browse/MONGOID/) on Jira that corresponds with this change we can triage and review.

**Comment by johnnyshields** [comment]
Please add Rspecs for this change

**Comment by johnnyshields** [comment]
@u16suzu this should probably be a global config `inspect_format = :expanded / :compact`. I have a lot of very large models, and while your way is far more readable, I think it would be good to have a compact mode as well to preserve the existing behavior.

**Comment by u16suzu** [comment]
@alexbevi 
Hi! thanks for your comment. Your comment is very helpful.
I will create issue for it after adding rspec and trimming the PR.

**Comment by u16suzu** [comment]
@johnnyshields 
Thanks for your comments.
I'm setting up a local DB environment right now and haven't been able to run mongoid's rspec locally yet.
I will add rspec after done it.

(The sample code in PR's description was collected by changing mongoid code at my local PC with my sample rails project.)

**Comment by u16suzu** [comment]
@johnnyshields 

> this should probably be a global config inspect_format = :expanded / :compact. 

yes. I totally agree with your opinion. Some people have huge model in mongodb.

I will add that setting.

**Comment by alexbevi** [comment]
Hi @u16suzu, after further review the team doesn't feel this feature will be accepted. We appreciate your suggestion and willingness to improve the Mongoid developer experience for all users and encourage you to continue submitting feedback to the [MONGOID project](https://jira.mongodb.org/browse/MONGOID/).

**Comment by u16suzu** [comment]
@alexbevi 
Sorry for the half-hearted PR.
I would like to thank the team for their response.

**Pull request closed without merging**
