### PR TITLE
Allow rails 6.0 and test rails 6.1 (master)

### PR DESCRIPTION
**Pull request by Fudoshiki**

### CODE REVIEW

**Comment by p-mongo** [comment]
This is being tracked in https://jira.mongodb.org/browse/MONGOID-4730. Until Rails 6 actually comes out, Mongoid cannot claim compatibility with it.

**Comment by tricknotes** [comment]
Rails 6 was already released..
https://github.com/rails/rails/tree/v6.0.0

Can we continue this PR?

**Comment by johnnyshields** [comment]
@p-mongo

**Comment by equivalent** [comment]
:pray:  pls @p-mongo

**Comment by equivalent** [comment]
I can confirm that once I used  this PR in my Gemfile( ` gem 'mongoid', git: 'git@github.com:Fudoshiki/mongoid.git' `)   it solves my issue with Rails 6.0.0 upgrade https://github.com/elastic/elasticsearch-rails/issues/904#issuecomment-523382646

so PR tested on a production application :) 

@Fudoshiki `#hero` `#legend`

**Comment by johnnyshields** [comment]
Please close in favor of #4652

**Comment by p-mongo** [comment]
Mongoid 7.0.5 has just been released with Rails 6 support.

**Pull request closed without merging**
