### PR TITLE
MONGOID-3074 Considering time zones while returning values of distinct query

### PR DESCRIPTION
**Pull request by sivagollapalli**

### CODE REVIEW

**Comment by durran** [comment]
The problem here is that if we are converting values returned from distinct, it cannot be *just* time values, it needs to be all values that have fields defined in the model. This will also simplify the code - one would just need to grab the field object and demongoize from there for each value in the array.

**Comment by sivagollapalli** [comment]
@durran Updated the PR as per your suggestions. Could you please review?

**Comment by sivagollapalli** [comment]
@durran Could you please let me know your comments?

**Comment by durran** [comment]
Looks great just needs to wait because it is a behaviour change and cannot go into a minor release or we break semver.

**Pull request merged**
