### PR TITLE
[READY FOR REVIEW] MONGOID-5509 Merge 8.1-stable (deprecation changes) to master

### PR DESCRIPTION
**Pull request by johnnyshields**
This PR merges branch `8.1-stable` into `master` after resolving conflicts. This includes the following changes:
- MONGOID-5509 / MONGOID-5490 - Removal of deprecated 7.x feature flags.
- Drop support for `config.load_defaults` versions "7.3", "7.4", "7.5", as their options are no longer available.
- Improved documentation around use of ActiveSupport time zones, vis-a-vis of removal of `use_activesupport_time_zone` option.
- Merge of `legacy_readonly` behavior/specs.
- Merge of 8.1 release notes for `Mongoid::Config.immutable_ids`.
- Merge of https://github.com/mongodb/mongoid/pull/5572 which fixes an issue with the deprecation logic on Ruby 2.7 and earlier.

Recommended to merge this without squashing commits, so that it will be easy to diff any future changes between `8.1-stable` and 9.0 etc.

### CODE REVIEW

**Comment by jamis** [comment]
Hey @johnnyshields -- thanks for this PR, and for keeping it up-to-date! I know your proposed plan was to merge this first, and then prepare another PR that removes the deprecated options, but I think my preference would be to have a single PR that wraps up the 9.0 side of MONGOID-5490 and MONGOID-5509, rather than drawing it out across multiple PRs. (Especially since the changes are minor.)

Would you be able to update this PR to remove those deprecated options, as well? I look forward to seeting that baggage from 7.x cleaned up!

**Comment by johnnyshields** [comment]
Sure, I'm glad to do one more commit for that.

I do think we should merge this without squashing commits so that the 8.x commit tree is merged in.

**Comment by johnnyshields** [comment]
@jamis on second thought, because we have to remove all usages of all the legacy feature flags, I think they should be done as smaller PRs. The diff is gonna be quite huge considering all the spec removals (entire logic branches of specs will be deleted.)

So let's merge this first, then I'm happy to follow-up with the additional smaller PRs.

**Comment by jamis** [comment]
Hey @johnnyshields -- I'm going to recommend again that you do this in a single PR. Multiple PRs make more work for us, which means it will take longer for us to process them. This in turn tends to make us prioritize those issues lower.

You are more than welcome to organize the work however you want on your end -- creating smaller sub-branches and merging them into the feature branch, or however you want to work it -- but the pull request itself represents the culmination of all of that, a single point at which the work comes together in a single unit, representing (in this case) the deprecation of the 7.x feature flags.

In this specific case, too, most of the work is actually _deleting_ code, not _adding_ code, and especially deleting _specs_, which means the pull request shouldn't be nearly as difficult to review as a PR that implements new logic.

So please, do bundle the final work into a single pull request, and I'll prioritize reviewing and merging that when it is done. I also want to emphasize that we do appreciate your passion for this project! Your care for the project and its future really shows, and that matters to us. Thank you for all you do!

**Comment by johnnyshields** [comment]
OK, that's surprising to me but understood and will do it how you request.

**Comment by johnnyshields** [comment]
@jamis ready for review now. Each config option removal has been put into its own commit. It would be ideal if you can merge without squashing commits so we have a good `git blame` record.

**Comment by jamis** [comment]
Thank you very much, Johnny! I just wanted to set expectations for this week -- it's "skunkworks 2023" at MongoDB this week (see [this post](https://www.mongodb.com/blog/post/skunkworks-2022-week-building-mongodb-engineers) for a summary of last year's skunkworks) so the Ruby team is putting all PRs and Jira tickets on hold until next week. If you don't hear from any of us this week, it's not because we're ignoring you, it's because company policy gives us permission to "go dark" for a bit. :)

I just wanted to make sure you knew that I've seen your reply, and that I really, really appreciate your quick work on this! I'll review it next Monday and will consider merging without squashing (it depends on how much noise that ultimately adds to the commit history).

Have a great week!

**Comment by johnnyshields** [comment]
@jamis no worries! Happy hacking!!

**Comment by jamis** [comment]
This looks fantastic, @johnnyshields. Thank you very much for your work on this. I'm inclined to squash-and-commit, though; there are just a *lot* of irrelevant commits in the history here and I'm not thrilled about leaving that trail behind. Also, I prefer having a feature land as a single commit, unless there's a compelling reason otherwise; you mentioned that you wanted to merge without squashing "so that it will be easy to diff any future changes", but squashed or not, diffing shouldn't be affected. I'll wait to merge this until tomorrow so you can clarify, if you want.

Again, thank you for your work on this!

**Comment by johnnyshields** [comment]
@jamis it's specifically this diff which is good to have clean:

https://github.com/mongodb/mongoid/compare/master...8.1-stable

This indicates there are 50 commits orphaned on `8.1-stable` which are not yet on `master`. Merging this *without* squashing commits will make it so 8.1-stable is marked in-sync with master.

(The alternative is, if you *do squash commits*, the next time we need to forward port changes from `8.1-stable` to `master` someone will again have to resolve all the same conflicts that I already spent time resolving here.)

It's not a huge deal, but I think it helps avoid errors. In the past I've found orphaned changes on the x.y-stable branches that never got merged to master.

**Comment by jamis** [comment]
@johnnyshields that makes sense. I'm sure dealing with those conflicts was no fun. However, historically, the Mongoid project has let the "stable" branches diverge from master, with backported (or ported forward) features being cherry-picked across, rather than merged. Is it this an optimal strategy for maintaining multiple parallel branches? For some things, yeah, and for some things, no. All things are subject to change, of course, but for now, I'm going to squash-merge this PR to avoid dirtying the history with the unrelated commits.

Again, thank you very much for your work on this; I really like the framework for deprecating feature flags that you've developed, and I think it'll be very handy moving forward.

**Pull request merged**
