### PR TITLE
DOCS-11633: add a top-level link to the releases

### PR DESCRIPTION
**Pull request by ccho-mongodb**
JIRA: https://jira.mongodb.org/browse/DOCS-11633

### CODE REVIEW

**Comment by p-mongo** [comment]
Thank you for the patch.

We have a section for major changes: https://docs.mongodb.com/mongoid/master/tutorials/mongoid-upgrade/

If I am honest, this is rather neglected currently. I had the thought to provide more information there (essentially copy the release summaries, but organized by major version instead of chronologically like the github releases page is). Would such an improved version of the upgrade page meet the requirements of https://jira.mongodb.org/browse/DOCS-11633 ?

**Comment by ccho-mongodb** [comment]
I think the reporter was looking for a changelog ("new features/bug fixes") rather than an upgrade guide. Since this information already exists in the repo, I thought it would be appropriate to surface this at the top level of the left navigation bar.
Is the issue that you're not confident that the changelog page contains enough information? If so, is there a better page to link to? Otherwise, is there anything we can help with to bring it up to your standards for release?

**Comment by p-mongo** [comment]
I think the "upgrading" and the "changelog" sections are in fact the same section - it is a section which lists changes from one version to the next. Our "upgrading" section is essentially a changelog, so perhaps renaming it is the way to go.

The ticket said:

> Currently, the Mongoid documentation located here does not contain a section that lists 'new features/bug fixes' in the new versions of Mongoid.

There is such a section in the documentation, it is https://docs.mongodb.com/mongoid/master/tutorials/mongoid-upgrade/ (but it is rather incomplete especially for the 7.0 series which has had features added to it over the last 2 years rather than only receiving bug fixes).

**Comment by ccho-mongodb** [comment]
Ok, if you want, I'll close this PR and JIRA ticket.

I wonder if you might consider including minor releases that are tagged branches somewhere on the [Upgrading Mongoid](https://docs.mongodb.com/mongoid/master/tutorials/mongoid-upgrade/) page since it currently only links to the changes for major releases and not minor releases (e.g. 7.x rather than including one for 7.0 as well as 7.1). For example: [Mongo JVM Drivers What's New section](https://mongodb.github.io/mongo-java-driver/4.0/whats-new/)

**Comment by p-mongo** [comment]
Yes, I think this certainly is needed at least for 7.0 and 7.1.

**Comment by ccho-mongodb** [comment]
Thanks, closing this PR and the associated JIRA ticket.

**Comment by p-mongo** [comment]
I'll leave this open so that I remember to address this.

**Comment by p-mongo** [comment]
Created https://jira.mongodb.org/browse/MONGOID-4852 to address this.

**Pull request closed without merging**
