### PR TITLE
MONGOID-5027 Rails 6.1 support

### PR DESCRIPTION
**Pull request by p-mongo**
https://jira.mongodb.com/browse/MONGOID-5027

### CODE REVIEW

**Comment by p-mongo** [comment]
https://jira.mongodb.org/browse/MONGOID-5027

**Comment by p-mongo** [comment]
Replacement for https://github.com/mongodb/mongoid/pull/4935.

**Review by alcaeus — APPROVED** [review]

**Review by durran — APPROVED** [review]
LGTM

**Comment by twhy** [comment]
Please release this fix ASAP, thank you!

**Comment by awesome** [comment]
# Rail 6.1.1 Dependency Error

```
# Gemfile
ruby '2.7.1'
gem 'rails', '6.1.1'
gem 'mongoid', '7.2.0'

$ bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    mongoid (= 7.2.0) x86_64-darwin-20 was resolved to 7.2.0, which depends on
      activemodel (< 6.1, >= 5.1)

    rails (~> 6.1.1) x86_64-darwin-20 was resolved to 6.1.1, which depends on
      activemodel (= 6.1.1)
```
---
# Fix while waiting for release 👍 🩹 
```
# Gemfile
ruby '2.7.1'
gem 'rails', '6.1.1'
gem 'mongoid', github: 'mongodb/mongoid', branch: '7.2-stable'

$ bundle install
Fetching https://github.com/mongodb/mongoid.git
[mongoid] Warning: No private key present, creating unsigned gem.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
[...]
Using rails 6.1.1
Bundle complete! 13 Gemfile dependencies, 70 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by bencrouse** [comment]
Any sense of when this might be released? Just trying to schedule some upgrade plans over here. Thanks.

**Comment by jmeattle** [comment]
It would be useful to get this released soon as it's blocking upgrades to Rails v6.1 (which was released over 2 months ago).

**Comment by p-mongo** [comment]
We are working on a release incorporating this PR, thank you for the feedback.

**Pull request merged**
