### PR TITLE
Update to use Rails 5.0.0.rc2

### PR DESCRIPTION
**Pull request by yonigozman**

### CODE REVIEW

**Comment by estolfo** [comment]
thanks!

**Comment by swistaczek** [comment]
Any chances that you will release --pre version of mongoid?

**Comment by estolfo** [comment]
Yes, we'll release a rc2 of mongoid 6 to support rails 5 rc2 soon.

**Comment by swistaczek** [comment]
@estolfo rails 5.0.0.0 has ben released yesterday :)

**Comment by estolfo** [comment]
Oh, I didn't see that this morning. Thanks, we'll release Mongoid 6 soon.

**Pull request merged**
