### PR TITLE
Drop collections instead of deleting their contents to fix CI on 2.6 servers

### PR DESCRIPTION
**Pull request by p-mongo**

### CODE REVIEW

**Comment by p-mongo** [comment]
I believe https://jira.mongodb.org/browse/RUBY-2432 is the actual problem, hence this PR shouldn't be necessary once 2432 is fixed but the drop/create in tx tests could be useful to keep.

**Comment by johnnyshields** [comment]
Would propose to drop support for MongoDB < 3.0 in the next major Mongoid version (8). Realistically no one should be using < 3.6

**Comment by p-mongo** [comment]
I don't think that is necessary. Most of the work is done for older version support is by the driver.

**Comment by p-mongo** [comment]
The issue was fixed in the driver.

**Pull request closed without merging**
