### PR TITLE
[WIP] Support Rails 5

### PR DESCRIPTION
**Pull request by greysteil**
Also continues support for Rails 4.

### CODE REVIEW

**Comment by simi** [comment]
https://github.com/mongodb/mongoid/pull/4234#issuecomment-177275173

**Comment by estolfo** [comment]
We will only support Rails 5 with Mongoid 6.0

**Comment by greysteil** [comment]
Fair enough. Will there be any other breaking changes in 6.0, and if so is there a reason for not wanting to support Rails 5.0 in Mongoid 5.0? Just thinking about how to make the transition as straightforward as possible.

**Comment by estolfo** [comment]
Traditionally, Mongoid releases a new major version to support a new major version of Rails. I can't say right now exactly what changes may be backwards breaking in Mongoid 6.0, as it won't be released for a few months yet. I would encourage you to keep an eye on the tickets in the Mongoid project marked for Mongoid 6.0 and review the changelog when it's released.

https://jira.mongodb.org/browse/MONGOID/fixforversion/15882/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

**Pull request closed without merging**
