### PR TITLE
MONGOID-5579: Mongoid 9.0: Ruby, JRuby, Rails version support drops

### PR DESCRIPTION
**Pull request by johnnyshields**
This commit does the following for Mongoid 9.0:
- Drop support for Ruby 2.6, Rails 5.2
- Support JRuby 9.4, drop JRuby 9.3 (both will be supported on Mongoid 8.1, so this is fine.)
- Deprecation of Ruby 2.7, Rails 6.0
- CI changes congruent with the above
- Remove deprecated #as_json :compact option
- Remove all tests/hacks related to use of I18n 1.0, since it is not longer usable with Rails 6.0
- Workaround JRuby issue with "Logger::#{level}".constantize to get specs to pass
- Fixes a few kwarg-related specs for Ruby 3.2
- Fix a Float-precision spec for JRuby
- Remove the rspec-mocks-diag hack gem in favor of standard rspec. See MONGOID-5581.

### CODE REVIEW

**Comment by johnnyshields** [comment]
Merged to [Mongoid Ultra](https://github.com/tablecheck/mongoid-ultra)

**Comment by johnnyshields** [comment]
@comandeo FYI I see you are working on this now.

**Comment by johnnyshields** [comment]
@comandeo by the way this isn't ready for review. It became stale so I am marking it as a draft for now. I will break it up into a series of smaller PRs

**Comment by comandeo** [comment]
Good to know, the title of the PR confused me

**Comment by johnnyshields** [comment]
@comandeo I'm going to close this PR. I've extracted the code cleanups to their own individual PRs. For the Evergreen / GH actions bumps (Ruby 2.7, Rails 6) please handle it from scratch.

**Pull request closed without merging**
