### PR TITLE
MONGOID-3246 Added spec such that 3246 is no longer a bug

### PR DESCRIPTION
**Pull request by sivagollapalli**
#3246

### CODE REVIEW

**Comment by estolfo** [comment]
Thanks for this @sivagollapalli 
The whole test suite is not passing though because you've redefined the Band class in the test, which has the consequence of affecting further tests that rely on the original definition. Can you update the test to use an existing model in the spec/app/models folder or to define a completely separate class? Thanks

**Comment by sivagollapalli** [comment]
@estolfo Update PR with new models.

**Comment by estolfo** [comment]
Thanks @sivagollapalli 
I'm wondering why you've created an rspec example and not used a context block? If there's any way you could convert it to a context block with a before block, that'd be great. The rest of the file uses describe and context blocks, so it would be nice to keep it consistent. Thanks!

**Comment by sivagollapalli** [comment]
@estolfo As it is just single test case so I thought don't need to use context block. Now I modified the test case as per your suggestions.

**Comment by estolfo** [comment]
thanks @sivagollapalli !

**Pull request merged**
