### PR TITLE
MONGOID-5078 add tests and documentation pertaining to atomic_selector usage in Mongoid

### PR DESCRIPTION
**Pull request by p-mongo**

### CODE REVIEW

**Comment by p-mongo** [comment]
https://jira.mongodb.org/browse/MONGOID-5078

**Comment by p-mongo** [comment]
This PR marks `shard_key_selector` private on the basis of it not being documented in the tutorial. It is possible that it should be part of the public API - I think this will be resolved as part of MONGOID-5078 and when this is done, appropriate documentation should be added to the tutorial.

cc @dalton-braze

**Comment by dalton-braze** [comment]
The new documentation, tests, and naming clarification (`shard_key_selector` and `shard_key_selector_in_db`) look good!

**Comment by comandeo** [comment]
👍

**Review by comandeo — APPROVED** [review]

**Pull request merged**
