### PR TITLE
MONGOID-4947 Return old behavior for #any? method when block is given

### PR DESCRIPTION
**Pull request by vsevolod**

### CODE REVIEW

**Comment by johnnyshields** [comment]
@vsevolod can you please add a test case to verify the behavior here?

**Comment by johnnyshields** [comment]
@p-mongo this looks very similar to https://jira.mongodb.org/browse/MONGOID-4914. Can we do a scan of the code anywhere else that we need to add `return super if block_given?`. I have a feeling `.find` and `.any?` probably aren't the only two methods which broke from 7.0 --> 7.1

**Comment by Neilshweky** [comment]
Hey there @vsevolod I took your PR and made one of my own. I added tests and incorporated use of patterns as well... Let me know what you think! https://github.com/mongodb/mongoid/pull/4846

**Comment by vsevolod** [comment]
Yeap. That looks good, thank you.

чт, 30 июл. 2020 г. в 23:06, Neilshweky <notifications@github.com>:

**Comment by johnnyshields** [comment]
@vsevolod let's close this MR in favor of #4846

**Comment by vsevolod** [comment]
Moved to: https://github.com/mongodb/mongoid/pull/4846

**Pull request closed without merging**
