### PR TITLE
MONGOID-5150 Use primary read preference for validates_uniqueness_of 

### PR DESCRIPTION
**Pull request by Neilshweky**
https://jira.mongodb.org/browse/MONGOID-5150

### CODE REVIEW

**Comment by p-mongo** [comment]
I cannot think of any objections to this particular change but shouldn't all validations then use the primary read preference?

**Comment by Neilshweky** [comment]
> I cannot think of any objections to this particular change but shouldn't all validations then use the primary read preference?
That would make sense honestly

**Comment by Neilshweky** [comment]
@p-mongo what other validations do we have that touch the database? Here are the contents of the `lib/mongoid/validatable/` directory:
- associated.rb - checks that the associated document is valid
- format.rb - checks the field value matches a regex
- length.rb - checks the length of a specific field value
- localizable.rb - Adds localization support to validations
- macros.rb - defines macros
- presence.rb - checks that the value exists for a field
- queryable.rb - Wrap the validation inside the an execution block that alert's the client not to clear its persistence options.
- uniqueness.rb - Hits the db

**Comment by Neilshweky** [comment]
> I was thinking of the custom validator methods (`validate :foo`) which would result in database calls. But if the only affected Mongoid validator is uniqueness maybe the current solution is sufficient.

If users make their own validators, should we be enforcing primary reads? The default read preference is primary, so if a user elects to use secondary reads, they are most likely doing it purposely. I vote that this solution is solution.

**Review by p-mongo — APPROVED** [review]

**Comment by p-mongo** [comment]
I copied the notes here in the ticket and approve this PR as it currently is.

**Comment by johnnyshields** [comment]
AFAIK the only validator which reads from the DB is `validates_uniqueness`. I would not want Mongoid to force custom validators (i.e. user-defined) to read from primary; the user can do that explicitly within the validator.

**Review by comandeo — APPROVED** [review]

**Pull request merged**
