### PR TITLE
MONGOID-5757 Fix validation checks so that all associated records are validated

### PR DESCRIPTION
**Pull request by jamis**
(Backporting https://github.com/mongodb/mongoid/pull/5881 from master to 8.0-stable.)

Changes made for [MONGOID-5704](https://jira.mongodb.org/browse/MONGOID-5704) introduced a regression that caused associated validations to stop after the first failure, rather than validating all associated records. This PR corrects the regression by fixing the short-circuited evaluation that was introduced in that earlier PR.

### CODE REVIEW

**Review by comandeo-mongo — APPROVED** [review]

**Comment by joelim41** [comment]
@comandeo-mongo, can we get a release cut for this backport to v8.0?

**Comment by jamis** [comment]
@joelim41 -- I'm hoping to cut a new release soon, perhaps next week if the stars align. Sorry for the delay on this.

**Comment by joelim41** [comment]
awesome, thank you!

**Comment by joelim41** [comment]
@jamis any updates on this?

**Comment by jamis** [comment]
Hey @joelim41, thanks for your patience on this. There's one more ticket currently blocking a release, but I'm hopeful we'll have a patch for the 8.0 series by this week.

**Pull request merged**
