### PR TITLE
MONGOID-4812 Allow id to be a regular field in models (not an alias of _id)

### PR DESCRIPTION
**Pull request by p-mongo**
https://jira.mongodb.com/browse/MONGOID-4812

### CODE REVIEW

**Comment by p-mongo** [comment]
https://jira.mongodb.org/browse/MONGOID-4812

**Comment by johnnyshields** [comment]
@p-mongo we might want to reconsider the API here in light of the request not to have an `_id` field at all (I think that was mainly for embedded docs)

**Comment by p-mongo** [comment]
What are you suggesting exactly?

**Comment by johnnyshields** [comment]
I guess the other one would be a separate PR. Nevermind.

**Review by durran — APPROVED** [review]
LGTM

**Pull request merged**
