### PR TITLE
MONGOID-5509: Deprecate all feature flags which were introduced in Mongoid 7.x

### PR DESCRIPTION
**Pull request by johnnyshields**
Also includes https://github.com/mongodb/mongoid/pull/5488 as there will be a conflict. Please merge that one first.

### CODE REVIEW

**Comment by johnnyshields** [comment]
Ready for review

**Comment by johnnyshields** [comment]
Specs failing on earlier Ruby versions for some reason. Need to check it.

**Comment by johnnyshields** [comment]
In addition to this, we need to deprecate load_defaults 7.x

**Comment by johnnyshields** [comment]
@jamis -- done

**Comment by jamis** [comment]
Thank you @johnnyshields! I like having this mini-framework for deprecating options, and testing that those options are deprecated.

**Pull request merged**
