### PR TITLE
Add dry-run db:mongoid:list_indexes and db:mongoid:list_undefined_indexes Rake tasks

### PR DESCRIPTION
**Pull request by johnnyshields**
Useful when you want to check state of indices without modifying them.

Prints to console (via logger). Output format looks like:

```
ModelNameA
  _id_
  my_index
ModelNameB
  (none)
ModelNameC
  _id_
  my_other_index
```

### CODE REVIEW

**Comment by estolfo** [comment]
Closing this, as there hasn't been discussion on it since 2014, nor any additional requests.

**Comment by johnnyshields** [comment]
@estolfo I think we should definitely have this. Index migrations are a huge pain because they lock the DB... we need to see what is going to change first.

**Comment by estolfo** [comment]
Hi @johnnyshields 
I don't see anything similar in Rails to this task. Do you know of anything?
This is pretty simple to write as a custom rake task and there aren't any thumbs up from other users so I would hesitate to add it to the codebase.

**Comment by johnnyshields** [comment]
ActiveRecord and Mongoid migrations work a bit differently. Rails has `rake db:migrate:status` which will show which migrations are pending, based on your "migrations" table. What I'm proposing would be the Mongoid equivalent--since there's no "migrations" table, you need to do a diff between the indexes specified in your model code and the indexes which are actually in MongoDB.

**Comment by estolfo** [comment]
Hi @johnnyshields 

Ok, I don't see the harm with putting this in then, as Rails has the db:migrate:status task. Would you mind updating the documentation to say it has been included in 6.0.0, and rebasing against master so the travis tests can run?

Thanks!
Emily

**Comment by johnnyshields** [comment]
@estolfo I'll rebase this PR soon.

**Comment by estolfo** [comment]
thanks @johnnyshields

**Comment by estolfo** [comment]
@johnnyshields 
Would you like to rebase this? You can update documentation too to say since 5.2.0

**Comment by johnnyshields** [comment]
Changes done, waiting for CI

**Comment by johnnyshields** [comment]
Hmmm looking at this PR I think I want to change the implementation... what we really need is an index DIFF task which diffs indexes defined in mongoid with whats in the DB. Please hold off on merging I'll do the change soon.

**Comment by johnnyshields** [comment]
Replaced by #4386

**Pull request closed without merging**
