### PR TITLE
[WIP] Support new invoke_before/invoke_after for Rails 5+

### PR DESCRIPTION
**Pull request by Fudoshiki**
## Setup Rails 5.0

- `export BUNDLE_GEMFILE=$PWD/Gemfile`
- `bundle`
- `rspec`

Build passed

## Setup Rails 5.1.0 master

- `export BUNDLE_GEMFILE=$PWD/gemfiles/rails_master.gemfile`
- `bundle`
- `rspec`

Failed 1 test
```
Failures:

  1) Mongoid::Interceptable when cascading callbacks when the parent has a custom callback when the child does not have the same callback defined when running the callbacks directly does not cascade to the child
     Failure/Error: Band.after_rearrange { }
     
     TypeError:
       can't dup NilClass
     # /Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/bundler/gems/rails-98faa2a6a12e/activesupport/lib/active_support/callbacks.rb:623:in `dup'
     # /Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/bundler/gems/rails-98faa2a6a12e/activesupport/lib/active_support/callbacks.rb:623:in `block in __update_callbacks'
     # /Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/bundler/gems/rails-98faa2a6a12e/activesupport/lib/active_support/callbacks.rb:621:in `reverse_each'
     # /Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/bundler/gems/rails-98faa2a6a12e/activesupport/lib/active_support/callbacks.rb:621:in `__update_callbacks'
     # /Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/bundler/gems/rails-98faa2a6a12e/activesupport/lib/active_support/callbacks.rb:671:in `set_callback'
     # /Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/bundler/gems/rails-98faa2a6a12e/activemodel/lib/active_model/callbacks.rb:145:in `block in _define_after_model_callback'
     # ./spec/mongoid/interceptable_spec.rb:499:in `block (6 levels) in <top (required)>'

Finished in 2 minutes 29.4 seconds (files took 4.33 seconds to load)
11054 examples, 1 failure, 3 pending

Failed examples:

rspec ./spec/mongoid/interceptable_spec.rb:506 # Mongoid::Interceptable when cascading callbacks when the parent has a custom callback when the child does not have the same callback defined when running the callbacks directly does not cascade to the child
```

Run `rspec spec/mongoid/interceptable_spec.rb` build passed

### Rails 5.0.0.1

Placed `puts callbacks.inspect` before https://github.com/rails/rails/blob/5-0-stable/activesupport/lib/active_support/callbacks.rb#L660

```ruby
      # Remove all set callbacks for the given event.
      def reset_callbacks(name)
        callbacks = get_callbacks name

        ActiveSupport::DescendantsTracker.descendants(self).each do |target|
          if name == :rearrange
            puts callbacks.inspect
          end
          chain = target.get_callbacks(name).dup
          callbacks.each { |c| chain.delete(c) }
          target.set_callbacks name, chain
        end

        self.set_callbacks name, callbacks.dup.clear
      end
```
Run `rspec`

### Result
ActiveSupport::Callbacks::CallbackChain with filled `@chain` and `@callbacks`
Build passed

```ruby
#<ActiveSupport::Callbacks::CallbackChain:0x007fbf8fad0588 @name=:rearrange, @config={:scope=>[:kind, :name], :terminator=>#<Proc:0x007fbf8fad2478@/Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:786>, :skip_after_callbacks_if_terminated=>true}, @chain=[#<ActiveSupport::Callbacks::Callback:0x007fbf8fad0c18 @chain_config={:scope=>[:kind, :name], :terminator=>#<Proc:0x007fbf8fad2478@/Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:786>, :skip_after_callbacks_if_terminated=>true}, @name=:rearrange, @kind=:after, @filter=#<Proc:0x007fbf8fad0f60@/Users/sharevari/repository/gems/mongoid/spec/mongoid/interceptable_spec.rb:499>, @key=70230362982320, @if=[#<ActiveSupport::Callbacks::Conditionals::Value:0x007fbf8fad0ee8 @block=#<Proc:0x007fbf8fad0e98@/Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/gems/activemodel-5.0.0.1/lib/active_model/callbacks.rb:141>>], @unless=[]>], @callbacks=#<ActiveSupport::Callbacks::CallbackSequence:0x007fbf8fac0908 @call=#<Proc:0x007fbf8fac0890@/Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506>, @before=[], @after=[#<Proc:0x007fbf8fac06b0@/Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:201>]>, @mutex=#<Thread::Mutex:0x007fbf8fad0538>>
```

### Rails master

Placed `puts callbacks.inspect` before https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L715

```ruby
        # Remove all set callbacks for the given event.
        def reset_callbacks(name)
          callbacks = get_callbacks name

          ActiveSupport::DescendantsTracker.descendants(self).each do |target|
            if name == :rearrange
              puts callbacks.inspect
            end
            chain = target.get_callbacks(name).dup
            callbacks.each { |c| chain.delete(c) }
            target.set_callbacks name, chain
          end

          set_callbacks(name, callbacks.dup.clear)
        end
```
Run `rspec`

### Result
ActiveSupport::Callbacks::CallbackChain with nil `@chain` and `@callbacks`
```ruby
#<ActiveSupport::Callbacks::CallbackChain:0x007f83e5f99190 @name=:rearrange, @config={:scope=>[:kind, :name], :terminator=>#<Proc:0x007f83e5f992a8@/Users/sharevari/.rvm/gems/ruby-2.3.1@mongoid/bundler/gems/rails-98faa2a6a12e/activesupport/lib/active_support/callbacks.rb:859>, :skip_after_callbacks_if_terminated=>true}, @chain=[], @callbacks=nil, @mutex=#<Thread::Mutex:0x007f83e5f990a0>>
```
Failed 1 test

### CODE REVIEW

**Comment by johnnyshields** [comment]
@Fudoshiki Rails 5.0.1 was released in Dec. Is this PR still needed?

**Comment by Fudoshiki** [comment]
@johnnyshields mongoid doesn't work with Rails 5.1.0.beta1. becouse in Rails 5.1 new callbacks system https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L715. This PR for support 5.1.0.beta1 from master branch

**Comment by johnnyshields** [comment]
@estolfo @Fudoshiki whats the status of this PR?

**Comment by Fudoshiki** [comment]
wip unless mongoid master doesn't pass rails master gemspec

пн, 10 апр. 2017 г., 20:27 Johnny Shields <notifications@github.com>:

**Comment by estolfo** [comment]
We do still have some work to do for supporting rails 5.1: https://travis-ci.org/mongodb/mongoid/jobs/220875209

**Comment by Fudoshiki** [comment]
we can close this it favor #4427

**Comment by estolfo** [comment]
thanks @Fudoshiki

**Pull request closed without merging**
