### PR TITLE
Update Mongoid driver test matrix.

### PR DESCRIPTION
**Pull request by p-mongo**
Add stable (2.10) and oldstable (2.9) configurations,
as well as the minimum one (2.5).

### CODE REVIEW

**Comment by johnnyshields** [comment]
Recommend to either:
1) add back testing for driver v2.7 (in addition to 2.8 and 2.9)   OR
2) update gemspec to drop support for driver < 2.8

**Comment by egiurleo** [comment]
It looks like `.evergreen/.evg.yml` is a configuration file that lists out all the types of tests you want to run and sets environment variables. Then, in `.evergreen/run-tests.sh`, you use the variables you set to figure out which Gemfile is appropriate for the tests you're about to run. Am I understanding this correctly?

Also, is there a guide to writing Evergreen configuration files that I can read?

**Comment by p-mongo** [comment]
That is correct. Evergreen documentation for configuration files (Evergreen calls them "project files") is here: https://github.com/evergreen-ci/evergreen/wiki/Project-Files

**Comment by egiurleo** [comment]
@p-mongo Thank you! I'll make sure to read these over.

**Pull request merged**
