### PR TITLE
MONGOID-5042 rails g mongoid:config is not working on Rails 6.1

### PR DESCRIPTION
**Pull request by awesome**
> ```
> # lib/rails/generators/mongoid/config/config_generator.rb
> module Mongoid
>   module Generators
>     class ConfigGenerator < Rails::Generators::Base
> 
>       def app_name
>         #
>         # 1A)
>         # https://api.rubyonrails.org/classes/Rails/Generators/NamedBase.html#method-i-application_name
>         #require 'rails/generators/actions'
>         #require 'rails/generators/named_base'
>         #Rails::Generators::NamedBase.new([""]).send(:application_name)
>         #
>         # --OR--
>         #
>         # 1B)
>         #Rails.application.class.name.split("::").first.underscore
>         # 
>         # 2)
>         # https://api.rubyonrails.org/classes/Module.html#method-i-module_parent_name
>         Rails.application.class.module_parent_name.underscore
>       end
> ```
> 
> 
> Ticket: https://jira.mongodb.org/browse/MONGOID-5042
> 
> Alternative PR: #4941

### CODE REVIEW

**Comment by awesome** [comment]
@p-mongo do you know about this git error cloning the submodule for testing? The submodule test-apps works, but https://github.com/mongodb-labs/mongo-ruby-spec-shared does not. Maybe a GitHub permissions setting on spec-shared?

```
$ git clone --recurse-submodules https://github.com/mongodb/mongoid.git mongoid_upstream
Cloning into 'mongoid_upstream'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 82186 (delta 35), reused 11 (delta 5), pack-reused 82132
Receiving objects: 100% (82186/82186), 16.12 MiB | 3.92 MiB/s, done.
Resolving deltas: 100% (56344/56344), done.
Submodule 'spec/shared' (git@github.com:mongodb-labs/mongo-ruby-spec-shared) registered for path 'spec/shared'
Submodule 'test-apps' (https://github.com/mongoid/mongoid-test-apps) registered for path 'test-apps'
Cloning into '/Users/dev/Documents/Repo/asmbl/mongoid_upstream/spec/shared'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mongodb-labs/mongo-ruby-spec-shared' into submodule path '/Users/dev/Documents/Repo/asmbl/mongoid_upstream/spec/shared' failed
Failed to clone 'spec/shared'. Retry scheduled
Cloning into '/Users/dev/Documents/Repo/asmbl/mongoid_upstream/test-apps'...
remote: Enumerating objects: 146, done.        
remote: Counting objects: 100% (146/146), done.        
remote: Compressing objects: 100% (96/96), done.        
remote: Total 146 (delta 41), reused 134 (delta 29), pack-reused 0        
Receiving objects: 100% (146/146), 25.16 KiB | 2.10 MiB/s, done.
Resolving deltas: 100% (41/41), done.
Cloning into '/Users/dev/Documents/Repo/asmbl/mongoid_upstream/spec/shared'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mongodb-labs/mongo-ruby-spec-shared' into submodule path '/Users/dev/Documents/Repo/asmbl/mongoid_upstream/spec/shared' failed
Failed to clone 'spec/shared' a second time, aborting
```

**Comment by awesome** [comment]
> @p-mongo do you know about this git error cloning the submodule for testing? The submodule test-apps works, but https://github.com/mongodb-labs/mongo-ruby-spec-shared does not. Maybe a GitHub permissions setting on spec-shared?
> 
> ```
> $ git clone --recurse-submodules https://github.com/mongodb/mongoid.git mongoid_upstream
> [...]
> Failed to clone 'spec/shared' a second time, aborting
> ```

@p-mongo ok, figured it out and fixed https://github.com/mongodb/mongoid/pull/4954 . Submodules were using both ssh and https. I'm lazy on a new laptop without ssh key pasted into GitHub account--only using oauth key via desktop client… Submitted PR with all submodules using https so this issue doesn't happen to future lazy contributors.

**Comment by awesome** [comment]
@p-mongo Hi there! I added tests to app_spec.rb for `~> Rails 6.1` and WFM. See attached: terminal output for running specific test `$ APP_TESTS=1 rspec spec/integration/app_spec.rb:90`. Please feel free to update PR as you see fit or LMK changes you want. Thanks!

[Terminal Saved Output6-success.txt](https://github.com/mongodb/mongoid/files/5870511/Terminal.Saved.Output6-success.txt)

**Comment by midnight-wonderer** [comment]
Hi @awesome,
I just send you a patch to preserve the functionality for the old versions of Rails.
https://github.com/awesome/mongoid/pull/1

I guessed their automated test would break otherwise.

**Comment by p-mongo** [comment]
This was merged as https://github.com/mongodb/mongoid/pull/4960, thank you.

**Pull request closed without merging**
